### ISSUE TITLE
CORRECT LICENSE

### ISSUE THREAD

**Issue by backtrader** [joequant/sptrader#16]
Your SPTrader is a subclass of `backtrader.Strategy` which is GPLv3+ licensed.

You cannot therefore apply this license:

> Modules in directories other than strategy are Copyright (c) 2016 Bitquant Research Laboratories (Asia) Limited Released under the Simplified BSD License

Correct the licensing of the entire package or a DCMA Takedown notice will be issued.

**Comment by backtrader** [comment]
Furthermore ... all "strategies" are subclasses of `backtrader.Strategy` and cannot be proprietary. The owners may retain IPR, but the code must comply with the GPLv3+

Correct that too.

> The modules in the directory "strategy" are copyright by their owners and may contain proprietary and confidential code, which are not intended for public release.

**Comment by joequant** [comment]
also I'm releasing everything as GPLv3+ for now.  There are modules which I developed that do not contain backtrader source, and I will convert those back to BSD.
